## Control Panel Module

## About state-card-tiles
## Original forum thread: https://community.home-assistant.io/t/custom-ui-button-panel/29513
## Official repo: https://github.com/c727/home-assistant-tiles

## Useful links
## Easy way to generate image for a tile: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
## Color blend: https://meyerweb.com/eric/tools/color-blend/

##################################################
## Customize
##################################################

homeassistant:
  customize:
  
    # Control Panel
    script.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        #color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#BBBEC2'
        entities:
          # Line 1 - TV
          - entity: switch.tv
            caption: 
            icon: mdi:monitor
            column: 1
            row: 1
          - entity: script.tv_h1
            icon: mdi:android
            column: 2
            row: 1
          - entity: script.tv_antena
            icon: mdi:radio-tower
            column: 3
            row: 1
          - entity: script.tv_voldown
            icon: mdi:mdi:volume-medium
            column: 4
            row: 1            
          - entity: script.tv_volup
            icon: mdi:mdi:volume-high
            column: 5
            row: 1
          - entity: switch.tv_mute
            icon: mdi:volume-off
            column: 6
            row: 1
            
          # Line - AC
          - entity: switch.ac
            caption: 
            icon: mdi:fan
            column: 1
            row: 2
          - entity: script.ac_hot
            icon: mdi:white-balance-sunny
            color: '#FF6633'
            column: 2
            row: 2
          - entity: script.ac_cold
            icon: mdi:mdi:snowflake
            color: '#4FA7FF'
            column: 3
            row: 2
            
          # Others
          - entity: script.mp_playpause
            icon: mdi:play-pause
            column: 1
            row: 3
          - entity: script.all_off
            icon: mdi:format-vertical-align-bottom
            column: 2
            row: 3
          - entity: script.sleep
            label: 25m
            column: 3
            row: 3
          - entity: script.sleep
            label: 2h
            column: 4
            row: 3
            
    # Kodi
    script.remote_control_kodi:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        entities:
          # Line 1
          - entity: script.kodi_cmd
            data: { value: Input.Home }
            icon: mdi:home
            column: 1
            row: 1
          - entity: script.kodi_cmd
            data: { value: Input.Up }
            icon: mdi:arrow-up
            column: 2
            row: 1
          - entity: script.kodi_play_something
            icon: mdi:creation
            column: 3
            row: 1
            
          # Line 2
          - entity: script.kodi_cmd
            data: { value: Input.Left }
            icon: mdi:arrow-left
            column: 1
            row: 2
          - entity: script.kodi_cmd
            data: { value: Input.ExecuteAction }
            icon: mdi:circle-outline
            column: 2
            row: 2
          - entity: script.kodi_cmd
            data: { value: Input.Right }
            icon: mdi:arrow-right
            column: 3
            row: 2
            
         # Line 3
          - entity: script.kodi_cmd
            data: { value: Input.Back }
            icon: mdi:keyboard-return
            column: 1
            row: 3
          - entity: script.kodi_cmd
            data: { value: Input.Down }
            icon: mdi:arrow-down
            column: 2
            row: 3
          - entity: script.kodi_playpause
            icon: mdi:play-pause
            column: 3
            row: 3
    
    # Moods
    script.remote_control_moods:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 5
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        #color: 'var(--paper-card-background-color)'
        entities:
          - entity: script.kodi_play_something
            icon: mdi:library-music
            column: 1
            row: 1          
          - entity: script.kodi_addon
            data: { value: plugin.audio.rainymood.com }
            icon: mdi:weather-lightning-rainy
            column: 2
            row: 1
          - entity: script.kodi_play_playlist
            data: { value: 1 }
            label: '80s'
            column: 3
            row: 1
          - entity: script.mp_nature
            icon: mdi:tree
            column: 4
            row: 1


##################################################
## Groups
##################################################

group:
  remote_control:
    name: Control Panel
    entities:
      - script.remote_control
      - sensor.last_command

  remote_control_kodi:
    name: Kodi
    entities:
      - script.remote_control_kodi
      - input_number.kodi_volume
      
  remote_control_moods:
    name: Moods
    entities:
      - script.remote_control_moods


##################################################
## Scripts
##################################################
            
script:
  remote_control:
    sequence:
  
  remote_control_kodi:
    sequence:
  
  remote_control_moods:
    sequence:
