## Triggers Module

##################################################
## Automations
##################################################

automation:

  # Startup
  - alias: 'Startup'
    hide_entity: True
    initial_state: 'on'    
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: frontend.set_theme
        data:
          name: darkblue
      - service: script.mode_normal
      - service: python_script.activity
      - service: python_script.summary
    
  # Call Service Event
  - alias: 'Call Service Event'
    hide_entity: True
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: script
    action:
      - delay: 00:00:02
      - service: python_script.last_cmd
        data_template: 
          event: "{{ trigger.event }}"

  # Time interval update (each 3 seconds)
  - alias: 'Time interval updates'
    hide_entity: True
    initial_state: 'on'
    trigger:
      - platform: time
        seconds: '/3'
    action:
      - service: python_script.summary
