## https://home-assistant.io/getting-started/
## https://home-assistant.io/cookbook/
## http://www.yamllint.com/


##################################################
## General
##################################################

homeassistant:
  name: Main
  # http://www.latlong.net/
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 8
  unit_system: metric
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  customize: !include config/customize.yaml
  customize_glob: !include config/customize_glob.yaml
  
  # https://home-assistant.io/docs/configuration/packages/
  packages:
    # Devices
    devices_tvs: !include config/packages/devices_tvs.yaml
    devices_acs: !include config/packages/devices_acs.yaml
    devices_tracker: !include config/packages/devices_tracker.yaml
    devices_status: !include config/packages/devices_status.yaml
    devices_control_phones: !include config/packages/devices_control_phones.yaml
    devices_control_pcs: !include config/packages/devices_control_pcs.yaml
    # General
    alarm: !include config/packages/alarm.yaml
    alarmclock: !include config/packages/alarmclock.yaml
    stats: !include config/packages/stats.yaml
    bots: !include config/packages/bots.yaml    
    media_center: !include config/packages/media_center.yaml
    mp_general: !include config/packages/mp_general.yaml
    profiles: !include config/packages/profiles.yaml
    internet: !include config/packages/internet.yaml
    system: !include config/packages/system.yaml
    weather: !include config/packages/weather.yaml    
    date: !include config/packages/date.yaml
    notify: !include config/packages/notify.yaml
    broadlink: !include config/packages/broadlink.yaml
    # Scenes/Scripts
    arrive_home: !include config/packages/arrive_home.yaml
    wakeup: !include config/packages/wakeup.yaml
    all_onoff: !include config/packages/all_onoff.yaml
    quotes: !include config/packages/quotes.yaml
    sleep: !include config/packages/sleep.yaml
    developer: !include config/packages/developer.yaml
    # UI Enhancements
    buttons: !include config/packages/buttons.yaml
    # TODO
    #webcams: !include config/packages/webcams.yaml
    #calendars: !include config/packages/calendars.yaml


##################################################
## Components
##################################################

http: !include config/http.yaml
ifttt: !include config/ifttt.yaml
mqtt: !include config/mqtt.yaml
tts: !include config/tts.yaml
#zwave: !include config/zwave.yaml

zone: !include config/zones.yaml
group: !include config/groups.yaml
weblink: !include config/weblinks.yaml
media_player: !include config/media_players.yaml
script: !include_dir_merge_named config/scripts/
automation old: !include_dir_merge_list config/automations/
panel_iframe: !include config/iframes.yaml
#automation: !include automations.yaml

#customizer: !include config/customizer.yaml
frontend: !include config/frontend.yaml
python_script:
config:
updater:
discovery:
conversation:
shopping_list:
sun:
#map:

recorder: !include config/recorder.yaml
logbook: !include config/logbook.yaml
history: !include config/history.yaml
logger: !include config/logger.yaml
