## https://home-assistant.io/getting-started/
## https://home-assistant.io/cookbook/
## http://www.yamllint.com/


##################################################
## General
##################################################

homeassistant:
  name: Main
  # http://www.latlong.net/
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 8
  unit_system: metric
  
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  customize: !include config/customize.yaml
  customize_glob: !include config/customize_glob.yaml
  
  # https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named config/packages/


##################################################
## Components
##################################################

http: !include config/http.yaml
ifttt: !include config/ifttt.yaml
mqtt: !include config/mqtt.yaml
tts: !include config/tts.yaml
#zwave: !include config/zwave.yaml

zone: !include config/zones.yaml
group: !include config/groups.yaml
weblink: !include config/weblinks.yaml
media_player: !include config/media_players.yaml
script: !include_dir_merge_named config/scripts/
automation old: !include_dir_merge_list config/automations/
panel_iframe: !include config/iframes.yaml
#automation: !include automations.yaml

#customizer: !include config/customizer.yaml
frontend: !include config/frontend.yaml
python_script:
config:
updater:
discovery:
conversation:
shopping_list:
#map:

recorder: !include config/recorder.yaml
logbook: !include config/logbook.yaml
history: !include config/history.yaml
logger: !include config/logger.yaml
