test2:  
  alias: Test 2
  sequence:
    - service: switch.broadlink_send_packet_192_168_0_3
      data:
        packet: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
