test2:  
  alias: Test 2
  sequence:
    - service: broadlink.send_packet_192_168_0_107
      data:
        packet: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
