## https://home-assistant.io/components/group/

##################################################
## Views
##################################################

default_view:
  view: yes
  icon: mdi:apps
  entities:
    - sensor.activity_badge
    - sensor.people_badge
    - sensor.inuse_badge
    - sensor.profile_badge
    - group.remote_control
    - group.remote_control_moods
    - group.summary

home:
  view: yes
  name: Home
  icon: mdi:home
  entities:
    - device_tracker.phone01_phone01
    #- device_tracker.phone_love
    #- device_tracker.phone_mother
    #- device_tracker.iphonedemario
    - sensor.dark_sky_temperature
    - sensor.dark_sky_hourly_summary
    #- sensor.dark_sky_daily_summary
    - alarm_control_panel.ha_alarm
    - sensor.countdown1_days
    #- group.summary
    #- group.scenes
    - group.living
    - group.office
    - history_graph.people
    
multimedia:
  view: yes
  name: Info
  icon: mdi:surround-sound
  entities:
    - group.mp_moods
    #- media_player.plex
    - media_player.clementine_remote
    - media_player.spotify
    - media_player.kodi
    
info:
  view: yes
  name: Info
  icon: mdi:information
  entities:
    - group.environment
    - group.internet
    - group.quote
    - group.about
    - group.stats

general:
  view: yes
  name: General
  icon: mdi:adjust
  entities:
    - group.alarmclock_wd
    - group.alarmclock_we
    - group.profile_onarrive
    - group.profile_onsleep
    - group.activity

devices:
  view: yes
  name: Info
  icon: mdi:mdi:router-wireless
  entities:
    - group.links_dev
    - group.devices_status
    - group.devices_phone01

learn:
  view: yes
  name: Learn
  icon: mdi:file-document
  entities:    
    - group.links_res
    - group.links_insp
    - group.links_int
    
setup:
  view: yes
  name: Setup
  icon: mdi:settings
  entities:
    - sensor.cpu_used
    - sensor.ram_available
    - sensor.disk_free_
    - group.system
    - group.scripts
    - group.tests
    - group.profile


##################################################
## Groups Links
##################################################

links_res:
  name: Resources
  entities:
    - weblink.Components
    - weblink.Releases
    - weblink.Podcast
    - weblink.Icons
    - weblink.Icons2

links_dev:
  name: Links
  entities:
    - weblink.plex
    - weblink.kodi
    - weblink.sonarr
    - weblink.torrent
    - weblink.tvguide
    - weblink.router

links_insp:
  name: Inspiration
  entities:
    - weblink.Cookbook
    - weblink.HomeAssistantConfig
    - weblink.CustomUI
    - weblink.Blog
    - weblink.BRUH
    - weblink.CCOSTAN
    - weblink.HackerHouse
    - weblink.NaturalNerd
    - weblink.Adafruit
    
links_int:
  name: Integrations
  entities:
    - weblink.Pushbullet
    - weblink.Telegram
    - weblink.IFFT
    - weblink.EventGhost


##################################################
## Groups General
##################################################

summary:
  name: Summary
  entities:
    - sensor.summary

internet:
  name: Internet
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
    - sensor.external_ip

about:
  name: About
  entities:
    #- sensor.tv_schedule_live
    #- sensor.tv_schedule_dw

stats:
  name: Statistics
  entities:
    - sensor.stats_tv1
    #- sensor.stats_work1

quote:
  name: Quote
  entities:
    - sensor.quote
    
system:
  name: System
  entities:
    - script.restart_ha
    - sensor.time_template
    - sensor.since_last_boot_template
    - sensor.version

devices_status:
  name: Devices Status
  entities:
    - sensor.broadlink_template
    - sensor.androidtv_template
    - sensor.tv_template

scenes:
  name: Scenes
  entities:
    #- script.arrive_home
    - script.mp_playpause
    - script.sleep
    - script.all_off

living:
  name: Living
  entities:
    - switch.tv_template
    - switch.tv_mute_template
    #- input_select.tv_channel
    - switch.ac_template

office:
  name: Office
  entities:
    - script.work
    - switch.pc_me_monitor

mp_moods:
  name: Moods
  entities:
    - script.mp_playpause
    - script.mp_radio
    - input_select.mp_radio_station
    - script.mp_podcast
    - script.mp_barney
    - script.mp_nature
    - script.mp_relax01
    - input_number.mp_volume

profile:
  name: Profile
  entities:  
    - input_select.ha_mode

scripts:
  name: Scripts
  entities:
    - script.refresh
    - script.ir_learn
    - script.arrive_home
    - script.wakeup
    #- script.all_off
    
tests:
  name: Tests
  entities:
    - script.test1
    - script.test2

##################################################
## People
##################################################

family:
  name: Family
  entities:
    - device_tracker.phone01_phone01
    - device_tracker.phone_mother
    - device_tracker.iphonedemario
