  #- platform: plex
  #  include_non_clients: true
  #  scan_interval: 10

  - platform: clementine
    host: !secret clementine_ip
  
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
